services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    env_file:
        - ./apps/.env
    expose:
        - 5432
    volumes:
        - ./dbs/postgresql-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7.2.5
    container_name: redis
    restart: always
    env_file:
        - ./apps/.env
    expose:
        - 6379
    volumes:
        - redis_data:/data/
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2s
      timeout: 60s
      retries: 5

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elastic
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    expose:
      - 9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green"]
      interval: 2s
      timeout: 60s
      retries: 5

  movies:
    container_name: movies
    build:
      context: ./apps/movies
    env_file: ./apps/.env
    depends_on:
      - postgres
      - elastic
      - redis
    restart: always
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  nginx:
    image: nginx:1.25.5
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/configs:/etc/nginx/conf.d:ro
    depends_on:
      - movies
  
  etl:
    build:
      context: ./apps/etl
    env_file: ./apps/.env
    depends_on:
      - postgres
      - elastic
    volumes:
      - etl_data:/usr/share/etl/data

volumes:
  elastic_data:
    name: elastic_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbs/es_data
  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbs/postgres-data
  redis_data:
    name: redis_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbs/redis-data
  etl_data:
    name: etl_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbs/etl-data
