line-length = 120
target-version = "py312"

[format]
quote-style = "double"

[lint.per-file-ignores]
"apps/movies/api/v1/endpoints/*" = ["B008"]

[lint]
select = [
    # https://docs.astral.sh/ruff/rules/
    # pycodestyle
    "E",
    "W",
    # to check McCabe complexity.
    "C",
    # quotes
    "Q",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pytest
    "PT",
    # pep8-naming (N)
    "N"
]


[lint.flake8-quotes]
inline-quotes = "double"

[lint.isort]
known-first-party = ["db", "settings", "api", "models", "services", "core"]
